sudo: required 
services:
  - docker
addons:
  -chrome: stable

before_install:
  - docker build -t mghoniem/docker-angular -f Dockerfile.dev .

script:
  - docker run mghoniem/docker-angular npm run test